FROM jenkins/inbound-agent:latest-jdk11 as jnlp

FROM ubuntu:hirsute

ARG TARGETPLATFORM
ARG BUILDPLATFORM

COPY --from=jnlp /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=jnlp /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar

RUN apt update \
    && apt install -y ca-certificates curl gnupg lsb-release apt-transport-https \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo \
         "deb [arch=$(echo $TARGETPLATFORM | cut -c7- ) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt update \
    && apt install -y docker-ce docker-ce-cli containerd.io

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]