FROM jenkins/inbound-agent:latest-jdk11 as jnlp

FROM node:12.22.5-alpine

RUN apk -U add openjdk8-jre git openssh

COPY --from=jnlp /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=jnlp /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]